-- Jalankan ini di SQL Editor Supabase Anda
-- Perhatian: Gunakan nama 'app_users' agar tidak bentrok dengan tabel internal Supabase

CREATE TABLE app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT DEFAULT 'Staff',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Template untuk 20 Pengguna (Silakan edit nama & password di sini)
INSERT INTO app_users (username, password, full_name, role)
VALUES 
('admin', 'komida12!', 'Rommy Admin', 'Administrator'),
('user01', 'pass01', 'Andi Pratama', 'Regional Manager'),
('user02', 'pass02', 'Budi Santoso', 'Branch Manager'),
('user03', 'pass03', 'Citra Lestari', 'FSA/MSA'),
('user04', 'pass04', 'Deni Wijaya', 'FSA/MSA'),
('user05', 'pass05', 'Eka Putri', 'Staff'),
('user06', 'pass06', 'Fajar Ramadhan', 'Staff'),
('user07', 'pass07', 'Gita Permata', 'Staff'),
('user08', 'pass08', 'Hadi Sucipto', 'Staff'),
('user09', 'pass09', 'Indah Sari', 'Staff'),
('user10', 'pass10', 'Joko Susilo', 'Staff'),
('user11', 'pass11', 'Kiki Amelia', 'Staff'),
('user12', 'pass12', 'Lina Marlina', 'Staff'),
('user13', 'pass13', 'Maman Suherman', 'Staff'),
('user14', 'pass14', 'Nana Suryana', 'Staff'),
('user15', 'pass15', 'Oman Rohman', 'Staff'),
('user16', 'pass16', 'Putu Gede', 'Staff'),
('user17', 'pass17', 'Qori Aina', 'Staff'),
('user18', 'pass18', 'Rian Hidayat', 'Staff'),
('user19', 'pass19', 'Santi Susanti', 'Staff'),
('user20', 'pass20', 'Tono Sudaryono', 'Staff');
